name: UpdateBinaries

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Clone StickyNet
      run: |
        git clone https://github.com/Playwo/StickyNet.git StickyNet
    - name: Clone Binaries
      run: |
        git clone https://github.com/Playwo/StickyNetBinaries.git Binaries
    - name: Build with dotnet
      run: |
        dotnet publish -c Release -o Binaries --self-contained --runtime linux-x64 StickyNet/
        cd Binaries
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Build newest version" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GHTOKEN }}
        repository: 'StickyNetBinaries'
